### ISSUE TITLE
추천 페이지 헤더바가 눌리지 않는 문제가 있습니다.

### ISSUE THREAD

**Issue by Puri12** [HANGHAE99-Group-04-Study/Sorting_Hat#8]
<img width="496" alt="image" src="https://user-images.githubusercontent.com/5901912/184041085-8b36b76f-3bdb-4ee8-a64d-9728d19c278a.png">

페이지 접속 시 위의 바가 클릭이 안되는 문제가 있습니다.
CSS쪽 문제인 것 같아서 문제 위치와 개선방안 작성해 보았습니다.
추후 해결하시면 아래 코멘트 후 이슈 닫아주시면 될 것 같아요!

### 문제 발생 예상 위치
```
        .section {
            width: 100%;
            height: 100%;
            position: relative;
        }
```

### 개선방안
```
        .section {
            width: 100%;
            height: 100%;
            display: flex;
            justify-content: center;
            align-items: center;
        }
```

**Comment by roses16-dev** [comment]
z-index수정
